/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package iceCreamShop;

import java.awt.Color;
import javax.swing.ButtonModel;

/**
 *
 * @author dsd10
 */
public class MyIceCreamShop extends javax.swing.JFrame {
    private static String price;

    /**
     * Creates new form MyIceCreamShop
     */
    public MyIceCreamShop() {
        initComponents();
        getContentPane().setBackground(new Color(246,242,242));
        rbChocolate.setActionCommand("Chocolate");
        rbVanilla.setActionCommand("Vanilla");
        rbStrawberry.setActionCommand("Strawberry");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgroupFlavour = new javax.swing.ButtonGroup();
        bgroupChoice = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        pnlChoice = new javax.swing.JPanel();
        rbCone = new javax.swing.JRadioButton();
        rbSundae = new javax.swing.JRadioButton();
        rbBananaSplit = new javax.swing.JRadioButton();
        btnCone = new javax.swing.JButton();
        btnSundae = new javax.swing.JButton();
        btnBananaSplit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlFlavour = new javax.swing.JPanel();
        cbFlake = new javax.swing.JCheckBox();
        cbSprinkles = new javax.swing.JCheckBox();
        cbSyrup = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlIceCream = new javax.swing.JPanel();
        rbChocolate = new javax.swing.JRadioButton();
        rbVanilla = new javax.swing.JRadioButton();
        rbStrawberry = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        lblPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Vivaldi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please Place Your Order");

        pnlChoice.setBackground(new java.awt.Color(246, 242, 242));
        pnlChoice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED)), "Ice Cream Choice", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(204, 0, 51))); // NOI18N

        bgroupChoice.add(rbCone);
        rbCone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbCone.setText("Cone");

        bgroupChoice.add(rbSundae);
        rbSundae.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbSundae.setSelected(true);
        rbSundae.setText("Sundae");

        bgroupChoice.add(rbBananaSplit);
        rbBananaSplit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbBananaSplit.setText("Banana Split");

        btnCone.setBackground(new java.awt.Color(246, 242, 242));
        btnCone.setForeground(new java.awt.Color(0, 0, 255));
        btnCone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cone.png"))); // NOI18N
        btnCone.setText("1.50");
        btnCone.setAlignmentX(1.0F);
        btnCone.setAlignmentY(0.0F);
        btnCone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCone.setSelected(true);

        btnSundae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sundae.png"))); // NOI18N
        btnSundae.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBananaSplit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bananasplit.jpg"))); // NOI18N
        btnBananaSplit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("€ 1.50");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setText("€ 1.90");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 102));
        jLabel4.setText("€ 2.50");

        javax.swing.GroupLayout pnlChoiceLayout = new javax.swing.GroupLayout(pnlChoice);
        pnlChoice.setLayout(pnlChoiceLayout);
        pnlChoiceLayout.setHorizontalGroup(
            pnlChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChoiceLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCone, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlChoiceLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(rbCone)))
                .addGroup(pnlChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChoiceLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnSundae, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBananaSplit, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(pnlChoiceLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(rbSundae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbBananaSplit)
                        .addGap(95, 95, 95))))
            .addGroup(pnlChoiceLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addGap(120, 120, 120)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(108, 108, 108))
        );
        pnlChoiceLayout.setVerticalGroup(
            pnlChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChoiceLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnlChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChoiceLayout.createSequentialGroup()
                        .addGroup(pnlChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSundae, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBananaSplit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbSundae)
                            .addComponent(rbBananaSplit)))
                    .addGroup(pnlChoiceLayout.createSequentialGroup()
                        .addComponent(btnCone, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbCone)))
                .addGap(19, 19, 19))
        );

        pnlFlavour.setBackground(new java.awt.Color(246, 242, 242));
        pnlFlavour.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Ice Cream Flavour", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(204, 0, 51))); // NOI18N
        pnlFlavour.setAutoscrolls(true);

        cbFlake.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbFlake.setText("Flake");

        cbSprinkles.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbSprinkles.setText("Sprinkles");

        cbSyrup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbSyrup.setText("Syrup");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 102));
        jLabel5.setText("€ 0.20");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 102));
        jLabel6.setText("€ 0.20");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 102));
        jLabel7.setText("€ 0.20");

        javax.swing.GroupLayout pnlFlavourLayout = new javax.swing.GroupLayout(pnlFlavour);
        pnlFlavour.setLayout(pnlFlavourLayout);
        pnlFlavourLayout.setHorizontalGroup(
            pnlFlavourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlavourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFlavourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFlavourLayout.createSequentialGroup()
                        .addComponent(cbSyrup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFlavourLayout.createSequentialGroup()
                        .addComponent(cbSprinkles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFlavourLayout.createSequentialGroup()
                        .addComponent(cbFlake)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(22, 22, 22))
        );
        pnlFlavourLayout.setVerticalGroup(
            pnlFlavourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlavourLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlFlavourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFlake)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFlavourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSprinkles)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFlavourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSyrup)
                    .addComponent(jLabel7))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlIceCream.setBackground(new java.awt.Color(246, 242, 242));
        pnlIceCream.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Ice Cream Flavour", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(204, 0, 51))); // NOI18N
        pnlIceCream.setAutoscrolls(true);

        bgroupFlavour.add(rbChocolate);
        rbChocolate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbChocolate.setSelected(true);
        rbChocolate.setText("Chocolate");

        bgroupFlavour.add(rbVanilla);
        rbVanilla.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbVanilla.setText("Vanilla");

        bgroupFlavour.add(rbStrawberry);
        rbStrawberry.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbStrawberry.setText("Strawberry");

        javax.swing.GroupLayout pnlIceCreamLayout = new javax.swing.GroupLayout(pnlIceCream);
        pnlIceCream.setLayout(pnlIceCreamLayout);
        pnlIceCreamLayout.setHorizontalGroup(
            pnlIceCreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIceCreamLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlIceCreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbStrawberry)
                    .addComponent(rbVanilla)
                    .addComponent(rbChocolate))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        pnlIceCreamLayout.setVerticalGroup(
            pnlIceCreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIceCreamLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(rbChocolate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbVanilla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbStrawberry)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 102));
        jLabel8.setText("TOTAL");

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 102));
        btnExit.setText("EXIT");

        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(255, 0, 102));
        btnPlaceOrder.setText("ORDER");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 0, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pnlFlavour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnPlaceOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)))
                                .addComponent(pnlIceCream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlIceCream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlFlavour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed

       
    }//GEN-LAST:event_btnPlaceOrderActionPerformed
public void calculatePrice(){
        Double price = 1.50;
       
        if (rbCone.isSelected()||btnCone.isSelected())
        price = 1.50;
        if (rbSundae.isSelected()|| btnSundae.isSelected())
        price = 2.10;
        if (rbBananaSplit.isSelected()|| btnBananaSplit.isSelected())
        price = 2.50;
        
        if(cbFlake.isSelected())
        price += .2;
        if(cbSprinkles.isSelected())
        price += .2;
        if(cbSyrup.isSelected())
        price += .2;
        lblPrice.setText("€" + price);
       System.out.println(price);

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyIceCreamShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyIceCreamShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyIceCreamShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyIceCreamShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        MyIceCreamShop m = new MyIceCreamShop();
        m.calculatePrice();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyIceCreamShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgroupChoice;
    private javax.swing.ButtonGroup bgroupFlavour;
    private javax.swing.JButton btnBananaSplit;
    private javax.swing.JButton btnCone;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnSundae;
    private javax.swing.JCheckBox cbFlake;
    private javax.swing.JCheckBox cbSprinkles;
    private javax.swing.JCheckBox cbSyrup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JPanel pnlChoice;
    private javax.swing.JPanel pnlFlavour;
    private javax.swing.JPanel pnlIceCream;
    private javax.swing.JRadioButton rbBananaSplit;
    private javax.swing.JRadioButton rbChocolate;
    private javax.swing.JRadioButton rbCone;
    private javax.swing.JRadioButton rbStrawberry;
    private javax.swing.JRadioButton rbSundae;
    private javax.swing.JRadioButton rbVanilla;
    // End of variables declaration//GEN-END:variables
}
