/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carHire;

import java.awt.Color;
import java.awt.List;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.ButtonModel;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author dsd10
 */
public class MyCarHire extends javax.swing.JFrame {

    private boolean appendToFile;//for the save to file action

    /**
     * Creates new form MyCarHire
     */
    public MyCarHire() {
        initComponents();
        getContentPane().setBackground(new Color(240, 248, 255));
        rbAny.setActionCommand("any transmission");
        rbManual.setActionCommand("manual transmission");
        rbAutomatic.setActionCommand("automatic transmission");

        rbFAny.setActionCommand("any fuel type");
        rbFPetrol.setActionCommand("petrol");
        rbFDiesel.setActionCommand("diesel");
        rbFHybrid.setActionCommand("hybrid");
        rbFBioethanol.setActionCommand("bioethanol");

        rb2.setActionCommand("2 seats");
        rb4.setActionCommand("4 seats");
        rb5.setActionCommand("5 seats");
        rb7.setActionCommand("7 seats");
        rb8.setActionCommand("8 seats");
        lstColour.setSelectedIndex(0);
        lstMake.setSelectedIndex(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Transmission = new javax.swing.ButtonGroup();
        FuelType = new javax.swing.ButtonGroup();
        NoOfSeats = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        lstMake = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        rJScrollPane = new javax.swing.JScrollPane();
        lstColour = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        rbManual = new javax.swing.JRadioButton();
        rbAutomatic = new javax.swing.JRadioButton();
        rbAny = new javax.swing.JRadioButton();
        rbFAny = new javax.swing.JRadioButton();
        rbFPetrol = new javax.swing.JRadioButton();
        rbFDiesel = new javax.swing.JRadioButton();
        rbFHybrid = new javax.swing.JRadioButton();
        rbFBioethanol = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnSaveToFile = new javax.swing.JButton();
        btnLoadFromFile = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        cmbModel = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 248, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 144, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MY CAR HIRE");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 144, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Model");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 144, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Colour");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 144, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Make");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 144, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("No. of Seats");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 144, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Fuel Type");

        lstMake.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lstMake.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Audi", "BMW", "Ford", "Honda", "Lexus", "Mazda", "Mitsubishi", "Toyota", "Volkswagen", "Dacia", "Trabant" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstMake.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstMake.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMakeValueChanged(evt);
            }
        });
        jScrollPane.setViewportView(lstMake);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 144, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Transmission");

        lstColour.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Black", "Blue", "Red", "Yellow", "Green", "Metallic", "Gray", "Silver", "White", "Brown", "Azure", "Burgundy", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstColour.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstColour.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstColourValueChanged(evt);
            }
        });
        rJScrollPane.setViewportView(lstColour);

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));

        Transmission.add(rbManual);
        rbManual.setSelected(true);
        rbManual.setText("Manual");
        rbManual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Transmission.add(rbAutomatic);
        rbAutomatic.setText("Automatic");

        Transmission.add(rbAny);
        rbAny.setText("Any");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAutomatic, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbAny)
                    .addComponent(rbManual))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rbAny)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbManual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbAutomatic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FuelType.add(rbFAny);
        rbFAny.setText("Any");

        FuelType.add(rbFPetrol);
        rbFPetrol.setSelected(true);
        rbFPetrol.setText("Petrol");

        FuelType.add(rbFDiesel);
        rbFDiesel.setText("Diesel");

        FuelType.add(rbFHybrid);
        rbFHybrid.setText("Hybrid");

        FuelType.add(rbFBioethanol);
        rbFBioethanol.setText("Bioethanol");

        NoOfSeats.add(rb2);
        rb2.setText("2");

        NoOfSeats.add(rb4);
        rb4.setText("4");

        NoOfSeats.add(rb8);
        rb8.setText("8");

        NoOfSeats.add(rb7);
        rb7.setText("7");

        NoOfSeats.add(rb5);
        rb5.setSelected(true);
        rb5.setText("5");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane3.setViewportView(txtArea);

        btnSaveToFile.setBackground(new java.awt.Color(240, 248, 255));
        btnSaveToFile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveToFile.setForeground(new java.awt.Color(30, 144, 255));
        btnSaveToFile.setText("Save to File");
        btnSaveToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveToFileActionPerformed(evt);
            }
        });

        btnLoadFromFile.setBackground(new java.awt.Color(240, 248, 255));
        btnLoadFromFile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLoadFromFile.setForeground(new java.awt.Color(30, 144, 255));
        btnLoadFromFile.setText("Load from File");
        btnLoadFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFromFileActionPerformed(evt);
            }
        });

        btnClearAll.setBackground(new java.awt.Color(240, 248, 255));
        btnClearAll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClearAll.setForeground(new java.awt.Color(30, 144, 255));
        btnClearAll.setText("Clear All");
        btnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllActionPerformed(evt);
            }
        });

        btnPlaceOrder.setBackground(new java.awt.Color(240, 248, 255));
        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(30, 144, 255));
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        cmbModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose make" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLoadFromFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaveToFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClearAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlaceOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbModel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbFHybrid)
                                    .addComponent(rbFBioethanol)
                                    .addComponent(rbFAny)
                                    .addComponent(rbFPetrol)
                                    .addComponent(rbFDiesel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb7)
                                    .addComponent(rb8)
                                    .addComponent(rb2)
                                    .addComponent(rb4)
                                    .addComponent(rb5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbFAny)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbFPetrol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbFDiesel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbFHybrid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbFBioethanol))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlaceOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveToFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoadFromFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearAll))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFromFileActionPerformed
        JFileChooser chooser = new JFileChooser();
         
        /* chooser.showDialog() opens the dialog. You must check if the
        user clicked the 'approve'/ ok button */
        if (chooser.showDialog(this, "OK") == JFileChooser.APPROVE_OPTION) {
             
            /* chooser.getSelectedFile(); will retrieve the file the
            user choose */
            File filename = chooser.getSelectedFile();
            /* Pass the filename into the FileReader constructor. */
            try (FileReader fr = new FileReader(filename);
                    BufferedReader br = new BufferedReader(fr)) {
 
                String line = "";           // Stores a line from the file
                String wholeFile = "";      // Stores each line from the
                                            // whole file
 
                /* br.readLine() reads a line of text from the file and 
                assigned it to 'line'.  readline() will return null when
                the end of file is reached, therefore it is checked in the
                condition to make sure it is not null. */
                while ( (line = br.readLine()) != null) {
                    //txtArea.setText(line);
                    /* Concat 'line' onto the 'wholeline' */
                    wholeFile += line + "\n"; 
                }
 
                // Add the wholeFile to the textArea once its not empty
                if (wholeFile.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "File is empty");
                } else {
                    txtArea.setText(wholeFile);
                }
 
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "File could not be opened");
            }
        }
    }//GEN-LAST:event_btnLoadFromFileActionPerformed

    private void lstMakeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMakeValueChanged
       String make = lstMake.getSelectedValue().toString();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        switch(make){
        case "Audi":
             model.addElement("A3");
             model.addElement("A4");
             model.addElement("A5");
             model.addElement("A6");
             model.addElement("A7");
             model.addElement("Q2");
             model.addElement("Q3");
             model.addElement("Q5");
             model.addElement("Q7");
         break;
            case "BMW":
             model.addElement("4 Series");
             model.addElement("5 Series");
             model.addElement("6 Series");  
         break;
            case "Ford":
             model.addElement("Focus");
             model.addElement("Fiesta");
             model.addElement("Transit"); 
             model.addElement("Fusion");
             model.addElement("Mustang");
             model.addElement("Escape"); 
        break;
            case "Honda":
             model.addElement("Civic");
             model.addElement("Accord");
             model.addElement("City");
             model.addElement("Ballade");
             model.addElement("Brio");
             model.addElement("BR-V");
        break;
            case "Lexus":       
             model.addElement("CT F Sport");
             model.addElement("IS F Sport");
             model.addElement("GS F Sport");  
             model.addElement("LS F Sport");
             model.addElement("RX F Sport");
             model.addElement("NX F Sport");
        break;
            case "Mazda": 
             model.addElement("MX-5");
             model.addElement("MAZDA2");
             model.addElement("MAZDA3");  
             model.addElement("MAZDA6");
             model.addElement("MAZDA CX-3");
             model.addElement("MAZDA CX-5");
          break;
            case "Mitsubishi":         
             model.addElement("Lancer");
             model.addElement("Outlander");
             model.addElement("Outlander PHEV");  
             model.addElement("Pajero");
         break;
            case "Toyota":           
             model.addElement("AYGO");
             model.addElement("Yaris");
             model.addElement("Auris Touring Sports ");  
             model.addElement("Corolla");   
             model.addElement("Avensis ");  
             model.addElement("Toyota C-HR");  
                
        break;
            case "Volkswagen":  
             model.addElement("Polo");
             model.addElement("Bora");
             model.addElement("Passat");  
             model.addElement("Golf");   
             model.addElement("Jetta");  
             model.addElement("Lavida"); 
             model.addElement("Caddy");  
             model.addElement("Amarok"); 
       break;
            case "Dacia":  
             model.addElement("Logan");
             model.addElement("Sandero");
             model.addElement("Duster");
             model.addElement("Logan MCV");
        break;
            case "Trabant":   
             model.addElement("Trabant 1");
             model.addElement("Trabant 2");
        break;
            default:
                model.addElement("Choose car Model");
        }
       
        cmbModel.setModel(model);
    }//GEN-LAST:event_lstMakeValueChanged

    private void btnSaveToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToFileActionPerformed
       if (txtArea.getText().isEmpty()){
        JOptionPane.showInternalMessageDialog(this, "Please place an order"); }
        else {
            //try(PrintWriter pw = new PrintWriter("order.txt")){
          //  pw.println(txtArea.getText());
             System.out.println("appendToFile" + appendToFile);
            try (FileWriter fw = new FileWriter(
                                 new File("order.txt"), appendToFile);
                    PrintWriter pw = new PrintWriter(fw)){
                
                pw.println(txtArea.getText());
         JOptionPane.showMessageDialog(this, "Order written to file"); 
        }catch(FileNotFoundException e){
            e.printStackTrace();
             JOptionPane.showMessageDialog(this, "File not found"); 
        }
            catch(IOException e){
            e.printStackTrace();
             JOptionPane.showMessageDialog(this, "Unable to create file"); 
        }
                }
 
    }//GEN-LAST:event_btnSaveToFileActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        btnSaveToFile.setEnabled(true);
         
        String order = "";

        String options = lstMake.getSelectedValuesList()
                            .toString();
         
        order += options.substring(1, options.length() - 1);
        order += " " + cmbModel.getSelectedItem().toString();
        order += ", " + lstColour.getSelectedValue().toString().toLowerCase();
   
       ButtonModel model = FuelType.getSelection();
        // model will be null if no drink is selected
        if (model != null) {
            order += ", ";
            order += model.getActionCommand();      
        }
         ButtonModel model1 = NoOfSeats.getSelection();
        // model will be null if no drink is selected
        if (model != null) {
            order += ", ";
            order += model1.getActionCommand();      
        }
         ButtonModel model2 = Transmission.getSelection();
        // model will be null if no drink is selected
        if (model != null) {
            order += ", ";
            order += model2.getActionCommand();      
        }
      
        // If the order String is empty show a message
        if (order.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please choose something");
        } else {
            txtArea.setText("Car specs: " + order + ".");
        }
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
         this.dispose();  
       // Create a new frame in memory, everything will be reset 
       new MyCarHire().setVisible(true);
    }//GEN-LAST:event_btnClearAllActionPerformed

    private void lstColourValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstColourValueChanged
       String colour = "";
       colour = lstColour.getSelectedValue().toString();
       
       
    }//GEN-LAST:event_lstColourValueChanged

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCarHire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCarHire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCarHire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCarHire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCarHire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup FuelType;
    private javax.swing.ButtonGroup NoOfSeats;
    private javax.swing.ButtonGroup Transmission;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnLoadFromFile;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnSaveToFile;
    private javax.swing.JComboBox cmbModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lstColour;
    private javax.swing.JList lstMake;
    private javax.swing.JScrollPane rJScrollPane;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rbAny;
    private javax.swing.JRadioButton rbAutomatic;
    private javax.swing.JRadioButton rbFAny;
    private javax.swing.JRadioButton rbFBioethanol;
    private javax.swing.JRadioButton rbFDiesel;
    private javax.swing.JRadioButton rbFHybrid;
    private javax.swing.JRadioButton rbFPetrol;
    private javax.swing.JRadioButton rbManual;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
